name: CI

on: [push]

env:
  AZURE: pplavetzki.azurecr.io 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make build-image
