name: Create Release

on:
  release:
    types: [published]

env:
  AZURE: pplavetzki
  SP_PASSWORD: ${{ secrets.SP_PASSWORD }}
  SP_APP_ID: 9bde9134-ec7a-41b1-9d16-a5ed9ec475cb
  ENV: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build, Test, and Publish
        run: make release